#!/usr/bin/expect -f
set ip [lindex $argv 0 ]
set user [lindex $argv 1 ]
set password [lindex $argv 2 ]
set proxy_ip [lindex $argv 3 ]
set proxy_user [lindex $argv 4 ]
set proxy_password [lindex $argv 5 ]
set timeout -1
set reuse "-oControlMaster=auto -oControlPersist=72h -oControlPath=~/.fastlogin/tmp/ssh_mux_%h_%p_%r"
if {$proxy_ip != "" && $proxy_user != "" && $proxy_password != ""} {
  set proxy "-oProxyCommand=ssh $reuse $proxy_user@$proxy_ip exec nc %h %p"
} else {
  set proxy ""
}

if {$proxy != ""} {
  spawn -noecho ssh $user@$ip -oNumberOfPasswordPrompts=1 $proxy
} else {
  spawn -noecho ssh $user@$ip -oControlMaster=auto -oControlPersist=72h -oControlPath=~/.fastlogin/tmp/ssh_mux_%h_%p_%r -oNumberOfPasswordPrompts=1
}
expect {
"*yes/no" { send "yes\r"; exp_continue }
"*$ip*password*:" { send "$password\r"; exp_continue }
"*password*:" { send "$proxy_password\r"; exp_continue }
"*Permission denied*" { exit 1 }
"*Could not resolve*" { exit 1 }
"*Connection closed*" { exit 1 }
"*Connection refused*" { exit 1 }
"*$*" { interact }
"*#*" { interact }
}

