#!/usr/bin/expect -f
set ip [lindex $argv 0 ]
set user [lindex $argv 1 ]
set password [lindex $argv 2 ]
set proxy_ip [lindex $argv 3 ]
set proxy_user [lindex $argv 4 ]
set proxy_password [lindex $argv 5 ]
set alive [lindex $argv 6 ]
set command [lindex $argv 7 ]
set timeout -1

if {$alive == ""} {
  if {$proxy_ip != "" && $proxy_user != "" && $proxy_password != ""} {
    set alive "72h"
  } else {
    set alive $proxy_ip
    set proxy_password $password
  }
}

if {$proxy_ip != "" && $proxy_user != "" && $proxy_password != ""} {
  spawn -noecho ssh $proxy_user@$proxy_ip -oControlMaster=auto -oControlPersist=$alive -oControlPath=~/.fastlogin/tmp/%h_%p_%r -oNumberOfPasswordPrompts=1
  expect {
    "*yes/no" { send "yes\r"; exp_continue }
    "*password*:" { send "$proxy_password\r"; exp_continue }
    "*Permission denied*" { exit 1 }
    "*Could not resolve*" { exit 1 }
    "*Connection closed*" { exit 1 }
    "*Connection refused*" { exit 1 }
    "*$*" {
      send "ssh $user@$ip\r"
	  expect {
		"*yes/no" { send "yes\r"; exp_continue }
		"*password*:" { send "$password\r"; exp_continue }
		"*Permission denied*" { exit 1 }
		"*Could not resolve*" { exit 1 }
		"*Connection closed*" { exit 1 }
		"*Connection refused*" { exit 1 }
		"*$*" {
		    if {$command != ""} {
                send "$command\r"
            }
            interact
            }
		"*#*" {
		    if {$command != ""} {
                send "$command\r"
            }
            interact
            }
      }
    }
    "*#*" {
      send "ssh $user@$ip\r"
	  expect {
		"*yes/no" { send "yes\r"; exp_continue }
		"*password*:" { send "$password\r"; exp_continue }
		"*Permission denied*" { exit 1 }
		"*Could not resolve*" { exit 1 }
		"*Connection closed*" { exit 1 }
		"*Connection refused*" { exit 1 }
		"*$*" {
            if {$command != ""} {
                send "$command\r"
            }
            interact
        }
		"*#*" {
            if {$command != ""} {
                send "$command\r"
            }
            interact
        }
      }
    }
  }
} else {
  spawn -noecho ssh $user@$ip -oControlMaster=auto -oControlPersist=$alive -oControlPath=~/.fastlogin/tmp/%h_%p_%r -oNumberOfPasswordPrompts=1
  expect {
    "*yes/no" { send "yes\r"; exp_continue }
    "*$ip*password*:" { send "$password\r"; exp_continue }
    "*password*:" { send "$password\r"; exp_continue }
    "*Permission denied*" { exit 1 }
    "*Could not resolve*" { exit 1 }
    "*Connection closed*" { exit 1 }
    "*Connection refused*" { exit 1 }
    "*$*" {
        if {$command != ""} {
            send "$command\r"
        }
        interact
    }
    "*#*" {
        if {$command != ""} {
            send "$command\r"
        }
        interact
    }
  }
}

